modLoader="javafml"
loaderVersion="[43,)"
license="Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
issueTrackerURL="https://github.com/Povstalec/StellarView/issues"
[[mods]]
modId="stellarview"
version="0.4.2"
displayName="Stellar View"
#logoFile="stellarview_large.png"
credits="Noobly Walker, tehgreatdoge, tristankechlo"
authors="Woldericz_Junior"
displayTest="IGNORE_ALL_VERSION"

description='''
Enjoy a Stellar View of the Sky
'''
[[dependencies.stellarview]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stellarview]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stellarview]]
    modId="enhancedcelestials"
    mandatory=false
    versionRange="[2.1.0.6,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.stellarview]]
modId="twilightforest"
mandatory=false
versionRange="[1.20.1-4.2.1518,)"
ordering="AFTER"
side="BOTH"
[[dependencies.stellarview]]
modId="aether"
mandatory=false
versionRange="[1.19.2-1.4.2,)"
ordering="AFTER"
side="BOTH"
