modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
issueTrackerURL="https://github.com/Povstalec/StellarView/issues"
[[mods]]
modId="stellarview"
version="0.4.2"
displayName="Stellar View"
#logoFile="stellarview_large.png"
credits="Noobly Walker, tehgreatdoge, tristankechlo"
authors="Woldericz_Junior"
displayTest="IGNORE_ALL_VERSION"

description='''
Enjoy a Stellar View of the Sky
'''
[[dependencies.stellarview]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stellarview]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stellarview]]
    modId="enhancedcelestials"
    mandatory=false
    versionRange="[6.0.1.3,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.stellarview]]
    modId="twilightforest"
    mandatory=false
    versionRange="[1.20.1-4.6.2941,)"
    ordering="AFTER"
    side="BOTH"
    [[dependencies.stellarview]]
    modId="aether"
    mandatory=false
    versionRange="[1.5.1,)"
    ordering="AFTER"
    side="BOTH"
