modLoader="javafml"
loaderVersion="[45,)"
license="Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
issueTrackerURL="https://github.com/Povstalec/StellarView/issues"
[[mods]]
modId="stellarview"
version="0.4.0"
displayName="Stellar View"
#logoFile="stellarview_large.png"
credits="Noobly Walker, tehgreatdoge, tristankechlo"
authors="Woldericz_Junior"
displayTest="IGNORE_ALL_VERSION"

description='''
Enjoy a Stellar View of the Sky
'''
[[dependencies.stellarview]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stellarview]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stellarview]]
    modId="enhancedcelestials"
    mandatory=false
    versionRange="[4.0.0.1,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.stellarview]]
modId="twilightforest"
mandatory=false
versionRange="[1.20.1-4.2.1696,)"
ordering="AFTER"
side="BOTH"
[[dependencies.stellarview]]
modId="aether"
mandatory=false
versionRange="[1.19.4-1.5.1,)"
ordering="AFTER"
side="BOTH"
